version: '3.8'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/usr/text-summariser
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://uctofthklwoiti:01980fe9be90ff8bddef123c2601bc805fbd459dd44fee35e8a7d55a9e8671a1@ec2-18-209-78-11.compute-1.amazonaws.com:5432/d91o84hk5ahjfc
        /d91o84hk5ahjfc
      - DATABASE_TEST_URL=postgres://uctofthklwoiti:01980fe9be90ff8bddef123c2601bc805fbd459dd44fee35e8a7d55a9e8671a1@ec2-18-209-78-11.compute-1.amazonaws.com:5432/d91o84hk5ahjfc
        /d91o84hk5ahjfc
    depends_on:
      - web-db

  web-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=uctofthklwoiti
      - POSTGRES_PASSWORD=01980fe9be90ff8bddef123c2601bc805fbd459dd44fee35e8a7d55a9e8671a1